"""add platform_message_id to messages

Revision ID: f06ddef3835f
Revises: 2b5c075445e1
Create Date: 2026-06-19 14:17:31.897471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06ddef3835f'
down_revision: Union[str, Sequence[str], None] = '2b5c075445e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('platform_message_id', sa.String(length=100), nullable=True, comment='ID сообщения в самой платформе (например, в Telegram)'))
    op.create_index(op.f('ix_messages_platform_message_id'), 'messages', ['platform_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_platform_message_id'), table_name='messages')
    op.drop_column('messages', 'platform_message_id')
    # ### end Alembic commands ###
